version: '3.8'

services:

  # Flask Application
  app:
    build: .
    container_name: payment_simulation_app
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    networks:
      - payment_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  payment_network:
    driver: bridge
