"""Add status and fraud fields to transactions

Revision ID: 34bfb6783323
Revises: 
Create Date: 2025-09-24 00:24:18.851403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bfb6783323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fraud_flag', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fraud_score', sa.Float(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE transactions SET status = 'pending' WHERE status IS NULL")
    op.execute("UPDATE transactions SET fraud_flag = false WHERE fraud_flag IS NULL")

    # Make status NOT NULL
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('fraud_score')
        batch_op.drop_column('fraud_flag')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
